### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated.

### ISSUE THREAD

**Issue by bernhard-hofmann** [Freegle/iznik-nuxt#3] opened 2019-10-22 06:43 UTC
When running the site with `npm run dev`, the following error message is displayed:

```ERROR  (node:22275) DeprecationWarning: Tapable.plugin is deprecated. Use new API on .hooks instead```

![image](https://user-images.githubusercontent.com/317632/67263297-8e8b9300-f49f-11e9-8c1c-3f124a901031.png)

**Comment by edwh** [comment] 2019-10-22 06:53
Yes.  I'm blithely ignoring that.  If you wanted to dig and understand 
whether it needs anything doing, that would be nice.

------ Original Message ------

**Comment by JayyajGH** [comment] 2019-10-22 08:06
This link has a description of what is likely to be the cause:

https://github.com/nuxt/create-nuxt-app/issues/185

Basically not an issue for now until @nuxtjs/pwa gets updated.  It's only a deprecation warning so can be ignored.

**Comment by edwh** [comment] 2019-10-22 08:10
Thanks @JayyajGH.  I don't know who you are, but that sounds convincing :-).  So I will close this issue.

**Closed by edwh** 2019-10-22 08:10 UTC
Labels: help wanted, invalid

**Comment by JayyajGH** [comment] 2019-10-22 09:54
Basically one of the packages you are using (or a package that your packages are using) are using a deprecated method in the tapable package.  It could be the pwa package I listed above or it could be another package that uses tapable. e.g. nuxt uses webpack.  webpack uses enhanced-resolve. enhanced-resolve uses tapable.

It should still be addressed at some point but it's not going to break anything for now.

Keeping the project dependencies up to date is probably the easiest way of keeping on top of stuff like this.  But also a major source of pain.  e.g. updating nuxt from the current 2.9.1 to the latest 2.10.2 might resolve it.  Or it might not.
